### ISSUE TITLE
안녕하세요? 진행상황 공유합니다. [+버그 공유]

### ISSUE THREAD

**Issue by Sonins** [cranemont/java-stock-crawler#3]
![image](https://user-images.githubusercontent.com/26663842/119228869-06c0ab80-bb50-11eb-849d-e0dc76438965.png)

뉴스는 위와 같이 뜨도록 만들었습니다. 링크도 추가해서 클릭하면 열 수 있게 할 거구용.

근데 밑에 scrollPane으로 바꾸니까 차트가 종목 더블 클릭하면 바로 안 뜨네요.

종목 더블 클릭하고 뉴스 뜬 다음에 위에 메뉴를 눌러야 업데이트가 됩니다..

예기치 않게 버그 하나 만들고 던져 놓는 것 같아서 죄송스러운 마음이네요. 어쨌든 공유합니다.

위에 윈도우 바는 없앴구요. 메뉴바 드래그하면 프레임 이동할겁니다.

**Comment by cranemont** [comment]
해결 완료 했습니다 :) 다시 그려주니까 잘 나오네요

차트에는 거래량과 이평선을 추가할 예정입니다.

시간이 된다면 관심종목들의 실시간 주가를 기록해서 급등 알람 기능을 만들고 싶은데 가능할지 모르겠네요

차트쪽 먼저 최대한 빨리 업데이트하고 알람 기능 구현해보겠습니다.

**Comment by Sonins** [comment]
네 알겠습니다. 

저도 a7f061727db5c18736924fde12ddc3691f4ef00b 을 마지막으로 뉴스 쪽 구현은 다 된 것 같아서 다른 기능 추가할 것 있으면 도와드릴게요.

버그 해결하셨다니 이슈는 닫겠습니다.
